# -*- coding: utf-8 -*-
"""Website.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jq0b7wV57jWDFQIPksIa_PS_UEH7EDhW
"""

# !pip install streamlit

# !streamlit hello

import streamlit as st
import pandas as pd
from io import StringIO
import cv2
import keras
import tensorflow as tf
import numpy as np
import tempfile
from matplotlib.image import imread

model_loaded = keras.models.load_model('./trained_model.keras')

uploaded_image = st.file_uploader("Choose a cloudy image: ", type=['jpg'])

if uploaded_image is not None:

  bytes_data = uploaded_image.getvalue()

  fp = tempfile.NamedTemporaryFile()
  fp.write(bytes_data)

  # bytes_data = uploaded_image.getvalue()
  st.image(bytes_data)

  img = cv2.imread(fp.name)

  fp.close()

  img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
  resize = tf.image.resize(img, (256, 256))
  np.expand_dims(resize, 0)
  test_prediction = model_loaded.predict(np.expand_dims(resize/255, 0))
  if test_prediction > 0.5:
    'It is a rain cloud'
    print("It is a rain cloud.")
  else:
    'It is a cloud'
    print("It is a cloud")

# uploaded_image.rea

# !streamlit run /usr/local/lib/python3.10/dist-packages/colab_kernel_launcher.py